name: weather_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0
  flutter_bloc: ^8.0.0
  built_value: ^8.0.0
  hydrated_bloc: ^9.1.5
  geolocator: ^8.0.0
  path_provider: ^2.1.4
  equatable: ^2.0.5
  built_collection: ^5.0.0
  intl: ^0.19.0
  easy_localization: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.0.0
  built_value_generator: ^8.0.0
  bloc_test: ^9.1.7
  mockito: ^5.0.0
  path_provider_platform_interface: ^2.0.4
  path_provider_macos: ^2.0.4


flutter:
  uses-material-design: true

  assets:
    - assets/translations/